# Generated by Django 5.2.15 on 2026-06-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraPostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Carrera de Postgrado',
                'verbose_name_plural': 'Carreras de Postgrado',
            },
        ),
        migrations.CreateModel(
            name='TipoRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Resolución',
                'verbose_name_plural': 'Tipos de Resolución',
            },
        ),
        migrations.CreateModel(
            name='ResolucionUniversitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('numero_ru', models.IntegerField()),
                ('seccion_origen', models.CharField(choices=[('Rectoria', 'Rectoría'), ('Postgrado', 'Postgrado'), ('Finanzas', 'Finanzas'), ('Otra', 'Otra')], max_length=20)),
                ('nombre_generado', models.CharField(blank=True, max_length=300)),
                ('archivo_pdf', models.FileField(upload_to='resoluciones/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('carrera_asociada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones', to='resoluciones.carrerapostgrado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones', to='resoluciones.tiporu')),
            ],
            options={
                'verbose_name': 'Resolución Universitaria',
                'verbose_name_plural': 'Resoluciones Universitarias',
            },
        ),
    ]
