# Generated by Django 5.2.15 on 2026-06-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrerapostgrado',
            name='sigla',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tiporu',
            name='sigla',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
