# Generated by Django 5.2.15 on 2026-06-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0002_carrerapostgrado_sigla_tiporu_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucionuniversitaria',
            name='vistos',
            field=models.ManyToManyField(blank=True, related_name='referenciada_en', to='resoluciones.resolucionuniversitaria'),
        ),
    ]
