# Generated by Django 5.2.15 on 2026-06-20 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resoluciones', '0003_resolucionuniversitaria_vistos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Programa',
                'verbose_name_plural': 'Tipos de Programa',
            },
        ),
        migrations.RemoveField(
            model_name='resolucionuniversitaria',
            name='vistos',
        ),
        migrations.AddField(
            model_name='carrerapostgrado',
            name='tipo_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='resoluciones.tipoprograma'),
        ),
        migrations.CreateModel(
            name='Visto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos', to='resoluciones.tipoprograma')),
            ],
            options={
                'verbose_name': 'Visto',
                'verbose_name_plural': 'Vistos',
            },
        ),
    ]
