# Generated by Django 5.2.15 on 2026-07-02 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolucionuniversitaria',
            options={},
        ),
        migrations.CreateModel(
            name='NombramientoDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_director', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('resolucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nombramiento_director', to='repositorio.resolucionuniversitaria')),
            ],
            options={
                'verbose_name': 'Resolución Universitaria',
                'verbose_name_plural': 'Resoluciones Universitarias',
            },
        ),
    ]
