# Generated by Django 5.2.15 on 2026-07-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_alter_resolucionuniversitaria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nombramientodirector',
            options={'verbose_name': 'Nombramiento de Director', 'verbose_name_plural': 'Nombramientos de Directores'},
        ),
        migrations.AlterModelOptions(
            name='resolucionuniversitaria',
            options={'verbose_name': 'Resolución Universitaria', 'verbose_name_plural': 'Resoluciones Universitarias'},
        ),
        migrations.AddField(
            model_name='resolucionuniversitaria',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resolucionuniversitaria',
            name='tamanio_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
