# Generated by Django 5.2.15 on 2026-07-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_alter_nombramientodirector_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucionuniversitaria',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
