# Generated by Django 5.2.15 on 2026-07-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Programa',
                'verbose_name_plural': 'Tipos de Programa',
            },
        ),
        migrations.CreateModel(
            name='TipoRU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Resolución',
                'verbose_name_plural': 'Tipos de Resolución',
            },
        ),
        migrations.CreateModel(
            name='CarreraPostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('tipo_programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='base.tipoprograma')),
            ],
            options={
                'verbose_name': 'Carrera de Postgrado',
                'verbose_name_plural': 'Carreras de Postgrado',
            },
        ),
        migrations.CreateModel(
            name='Visto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistos', to='base.tipoprograma')),
            ],
            options={
                'verbose_name': 'Visto',
                'verbose_name_plural': 'Vistos',
            },
        ),
    ]
